theme: jekyll-theme-minimal
title: 'Assembling and Annotating Bacterial Genomes Using PacBio Long Reads'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /
  - title: Welcome
    url: /markdown_docs/welcome
  - title: Technology, Data, and Experimental Design
    url: /markdown_docs/pacbio
  - title: Assembly, Assembly Metrics, and Quality Control
    url: /markdown_docs/assembly
  - title: Annotation
    url: /markdown_docs/annotation
  - title: Typing and Comparative Analyses
    url: /markdown_docs/Bacterial-taxonomy
  - title: Support
    url: support
